name: $(Date:yyyyMMdd)$(Rev:.r)
variables:
  buildConfiguration: 'Release'

trigger:
- master

stages:
- stage: Build
  jobs:
  - job: BuildJob
    pool: Default
    steps:
    - task: CmdLine@2
      inputs:
        script: |
          echo Write your commands here
          echo Hello $(buildConfiguration)
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        feedsToUse: 'select'
        vstsFeed: '501e0fcb-cbfb-4cc8-ad22-6a285a92bdb5'
    - task: DotNetCoreCLI@2
      displayName: 'dotnet build $(buildConfiguration)'
      inputs:
        command: 'build'
        configuration: $(buildConfiguration)
    - task: CopyFiles@2
      inputs:
        Contents: '**/bin/$(buildConfiguration)'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Test
  jobs:
  - job: TestJob
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '*.sln'
      continueOnError: true
- stage: Deploy
  jobs:
  - job: PublishJob
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
  - job: DeployJob
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
      